### PR TITLE
Update linux aarch64 and ppc64le CI providers to default

### PR DESCRIPTION
**Pull request by dbast**
Default builds on native hardware, which is more reliable.

Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dbast** [comment]
@conda-forge-admin, please rerender

**Comment by dbast** [comment]
This is derived from the after merge discussion of https://github.com/conda-forge/ripgrep-feedstock/pull/5

@jayfurmanek @jakirkham @isuruf

**Comment by dbast** [comment]
The native builds are fast compared to azure... even faster than the win azure build ... :)

Travis is triggered twice and one of it is failing ... what to do about that?

The error is:
```
Status: Downloaded newer image for condaforge/linux-anvil-ppc64le:latest
standard_init_linux.go:190: exec user process caused "exec format error"
The command "if [[ ${PLATFORM} =~ .*linux.* ]]; then ./.travis/run_docker_build.sh; fi" exited with 1.
```

**Comment by dbast** [comment]
@conda-forge-admin, please rerender

**Comment by jakirkham** [comment]
What's also interesting is the other Travis CI job seems to be [using `x86_64`]( https://travis-ci.com/conda-forge/ripgrep-feedstock/builds/128478788#L29 ); hence, we see a failure there.

**Comment by jakirkham** [comment]
@jayfurmanek, does Travis CI only provide `ppc64le` images on the `.org` domain or do they provide them on the `.com` domain as well?

**Comment by jayfurmanek** [comment]
Only on .org (for now). I’m not sure why the .com shows up in some feedstocks. It shouldn’t. In some other feedstocks we just ignored it.

**Comment by dbast** [comment]
@jayfurmanek Thanks for confirmation.... I am also seeing that travis behaviour in random other feedstocks... mostly ignored that, because it has not consequence.

**Comment by dbast** [comment]
Ok. ignoring the non-relevant second failing travis run.

**Pull request merged**
