### PR TITLE
Update recipe

### PR DESCRIPTION
**Pull request by dbast**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Closes https://github.com/conda-forge/ripgrep-feedstock/issues/3

### CODE REVIEW

**Comment by dbast** [comment]
@jakirkham Adding `{{ compiler("c") }}` + rerender brings in a c compiler matrix for windows (vs2008, vs2015), which is wrong here, as this is a rust recipe. I tend to remove it again. Any other solution? Skipping via `skip: True  # [win and vc<14]`?

**Comment by jakirkham** [comment]
Maybe use a `unix` selector on the compiler. Windows probably needs the msys2 compiler for an equivalent affect.

**Comment by dbast** [comment]
@conda-forge-admin, please rerender

**Comment by jakirkham** [comment]
Thanks @dbast!

**Pull request merged**
