### PR TITLE
Add thirdparty license to build

### PR DESCRIPTION
**Pull request by sstadick**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

(@dbast I'm making this PR because I was asked to as part of the below linked issue. I apologize for the out of the blue nature of it. Even if you don't want to merge it can at least be pointed to as an example of how to add thirdparty info to a feedstock without modifying the source repo).

This PR adds the THRIDPARTY license information for ripgrep as outlined here: https://github.com/conda-forge/conda-forge.github.io/issues/1052.

To do this I pulled the latest `ripgrep` source from the releases page, untarred, and ran `cargo bundle-license -f yaml -o THIRDPARTY.yml` and then filled in the licenses that were missing. I copied that file into the recipe dir here and set up the build to check for changes. 

Alternatively, the THIRDPARTY file could be added to `ripgrep` itself, see https://github.com/conda-forge/staged-recipes/pull/16110 and https://github.com/conda-forge/staged-recipes/pull/16111 for an example of that.

For future versions of ripgrep this would necessitate regenerating the thirdparty file, ideally as part of the CI that makes the PR into the feedstock, but I'm not sure how to do that.

### CODE REVIEW

**Comment by sstadick** [comment]
@conda-forge-admin, please rerender

**Comment by sstadick** [comment]
@conda-forge-admin please restart ci

**Comment by sstadick** [comment]
@dbast I think this is ready for a review / discussion if you're interested in this being added here instead of in `ripgrep` itself.

**Comment by dbast** [comment]
@sstadick Thanks. We afaik need to distribute all listed Licenses via the created conda package. What is the goal of having the THIRDPARTY.yml file as part of this repo?:
* Comparing manually that the license_file entry in the meta.yaml is complete? or
* Adding the THIRDPARTY.yml to the created package to have all licenses automatically included?

**Comment by sstadick** [comment]
The latter:

- Adding `THIRDPARTY.yml` satisfies the requirement [here](https://github.com/conda-forge/conda-forge.github.io/issues/1052) for including all licenses of dependencies.
- `cargo-bundle-licenses` checks to make sure that the `THIRDPARTY.yml` file is up to date with the actual deps.

When ripgrep comes out with a new version, as it stands now, `THRIDPARTY.yml` would have to be updated in this repo manually via `cargo bundle-licenses --format yaml --output NEW.THIRDPARTY.yml --previous recipe/THIRDPARTY.yml` and then move new over old once any warnings are resolved.

What I realize isn't done here is adding `THIRDPARTY.yml` to the `meta.yaml`. I _think_ it can just be added to the `license_file` part?

**Comment by dbast** [comment]
Well, there is no requirement to have the licenses as part of the repo here. The requirements is to list all the licenses as list via the license_file entry in the meta.yaml to have the licenses included in the resulting conda packages. So the question is: how to get from the generated and updated THRIDPARTY.yml to a valid list of file references for the license_file entry?

**Comment by sstadick** [comment]
I mean, if a little hand-wavyness is okay, instead of having `cargo-bundle-licenses` work off of a stored version here, during the build it could create a `THIRDPARTY.yml` as a best effort attempt that will likely have a few "NOT FOUND" values in it, and then just list the `THIRDPARTY.yml` in the `meta.yml`, as the thirdparty file has both the license, and the license text in it for every dependency of ripgrep. 

So the license_file section would look like:

```yaml
  license_file:
    - LICENSE-MIT
    - THIRDPARTY.yml
```

and require no extra maintainer input.

**Comment by dbast** [comment]
Ok. Added THIRDPARTY.yml as license_file entry.

**Comment by sstadick** [comment]
I've removed the THIRDPARTY file in the repo and updated the builds to just generate a THIRDPARTY.yml.

If you / others are okay with this pattern, I really like it. It adds no maintenance burden, new ripgrep updates should just work, and performs a best effort addition of third-party licenses and texts.

**Pull request merged**
